Repository Crownicles/Crownicles, pull requests merged in 2020-11, with the labels that each got.

#240 Fix du nom objets
  resources/text/objects/35.json
  resources/text/objects/36.json
  resources/text/objects/37.json
Labels: typo / visu

#247 Fix badge bug majeur
  resources/text/commands/profile.json
Labels: typo / visu

#256 Ajout commande rarity
  resources/text/commands/help.json
  resources/text/commands/rarity.json
  src/commands/player/Rarity.js
Labels: command, enhancement

#257 Ajout de la commande idea
  resources/text/commands/help.json
  resources/text/commands/idea.json
  src/commands/player/IdeaCommand.js
Labels: command, enhancement

#258 Fix + Alias + Ajout d'items
  resources/text/armors/39.json
  resources/text/commands/help.json
  resources/text/objects/45.json
  resources/text/objects/48.json
  resources/text/objects/49.json
  resources/text/potions/42.json
  resources/text/weapons/73.json
  resources/text/weapons/74.json
  src/commands/player/HelpCommand.js
  src/commands/player/InventoryCommand.js
  src/commands/player/ProfileCommand.js
  src/commands/player/TopCommand.js
  src/commands/player/UpdateCommand.js
Labels: command, enhancement, items

#260 merge guildFix
  resources/text/commands/guildAdd.json
  resources/text/commands/guildDescription.json
  resources/text/commands/guildElder.json
  resources/text/commands/guildKick.json
  resources/text/commands/guildLeave.json
  src/commands/guild/GuildAddCommand.js
  src/commands/guild/GuildCreateCommand.js
  src/commands/guild/GuildDescriptionCommand.js
  src/commands/guild/GuildElderCommand.js
  src/commands/guild/GuildKickCommand.js
Labels: bug

#267 pet commands folder #266
  src/commands/pets/BreedPetCommand.js
  src/commands/pets/MyPetCommand.js
  src/commands/pets/PetFreeCommand.js
  src/commands/pets/PetNicknameCommand.js
  src/commands/pets/PetTradeCommand.js
  src/commands/pets/PetTransferCommand.js
Labels: refactoring

#278 ajout d'un alias pour le shelter (sh)
  src/commands/guild/GuildShelterCommand.js
Labels: enhancement
