Repository Crownicles/Crownicles, pull requests merged in 2020-09, with the labels that each got.

#183 Fix frozen effectt
  src/core/MessageError.js
Labels: bug

#191 fix typo #189
  ressources/text/events/42.json
Labels: event, typo / visu

#195 Ajout items + Fix event 42
  ressources/text/armors/38.json
  ressources/text/events/42.json
  ressources/text/objects/44.json
  ressources/text/objects/45.json
  ressources/text/objects/46.json
  ressources/text/objects/47.json
  ressources/text/potions/41.json
Labels: event, items, typo / visu

#196 typo readme
  README.md
Labels: github, typo / visu

#202 fix bug potion shop
  ressources/text/potions/35.json
  ressources/text/potions/36.json
  ressources/text/potions/37.json
  ressources/text/potions/38.json
  ressources/text/potions/39.json
  ressources/text/potions/40.json
Labels: typo / visu

#204 Update help link
  ressources/text/commands/help.json
Labels: typo / visu

#197 Modification appellation #165
  ressources/text/commands/listItems.json
  ressources/text/commands/shop.json
  ressources/text/commands/switch.json
  ressources/text/items.json
Labels: typo / visu

#207 fix potion bug #206
  src/commands/player/DrinkCommand.js
Labels: bug
