Repository Crownicles/Crownicles, pull requests merged in 2020-10, with the labels that each got.

#212 small indent fixes
  .gitignore
  ressources/text/commands/guildAdd.json
  ressources/text/commands/guildCreate.json
Labels: refactoring, typo / visu

#213 guildDescription
  database/migrations/008-guild-description.sql
  ressources/text/commands/guild.json
  ressources/text/commands/guildDescription.json
  ressources/text/commands/help.json
  src/commands/guild/GuildCommand.js
  src/commands/guild/GuildDescriptionCommand.js
  src/core/Constant.js
  src/core/models/Guilds.js
Labels: command, enhancement

#216 Fix resetbadge command
  ressources/text/commands/resetBadgeCommand.json
Labels: bug

#217 Add text for issue #179
  ressources/text/bot.json
  src/core/Command.js
Labels: core, enhancement

#218 Change message #178
  ressources/text/commands/inventory.json
  ressources/text/commands/sell.json
Labels: enhancement, typo / visu

#224 typo
  ressources/text/commands/guildAdd.json
Labels: typo / visu

#222 Ajout de l'event 46
  ressources/text/events/46.json
Labels: event

#232 Ajout d'un badge
  ressources/text/commands/profile.json
Labels: enhancement
