Repository Crownicles/Crownicles, pull requests merged in 2021-06, with the labels that each got.

#432 Typographies
  resources/text/advices.json
  resources/text/maplocations/24.json
  resources/text/small_events/class.json
  resources/text/small_events/interactOtherPlayers.json
  resources/text/small_events/smallBadEvent.json
  resources/text/small_events/winGuildXP.json
Labels: typo / visu

#453 Refactor embeds
  .eslintignore
  package.json
  src/commands/admin/TestCommand.js
  src/core/Command.js
  src/core/Database.js
  src/core/DraftBot.js
  src/core/fights/Attack.js
  src/core/messages/DraftBotReaction.ts
  src/core/messages/DraftBotReactionMessage.ts
  src/index.js
  test/unit/core/Tools.test.ts
  test/unit/core/messages/DraftBotReactionMessage.test.ts
  tsconfig.json
Labels: refactoring

#462 Fix typos
  resources/text/smallEvents/class.json
  resources/text/smallEvents/findPotions.json
  resources/text/smallEvents/interactOtherPlayers.json
  resources/text/smallEvents/pet.json
  resources/text/smallEvents/staffMember.json
Labels: typo / visu

#459 Ajout d'un nouvel item donateur
  resources/text/objects/59.json
Labels: items

#461 Fix #435 food sell
  src/commands/guild/GuildShopCommand.js
  src/core/Tools.js
  src/core/smallEvents/findPetSmallEvent.js
  src/core/smallEvents/petSmallEvent.js
Labels: bug
