Repository Crownicles/Crownicles, pull requests merged in 2021-04, with the labels that each got.

#375 Fix pettransfer
  src/commands/pets/PetTransferCommand.js
Labels: bug

#384 Change animal to familier #383
  resources/text/commands/guildDaily.json
  resources/text/commands/guildShelter.json
  resources/text/commands/help.json
  resources/text/commands/myPet.json
  resources/text/commands/petFeed.json
  resources/text/commands/petFree.json
  resources/text/commands/petNickname.json
  resources/text/commands/petSell.json
  resources/text/commands/petTrade.json
  resources/text/commands/petTransfer.json
  resources/text/commands/profile.json
  resources/text/commands/shop.json
  resources/text/error.json
  resources/text/pets/0.json
Labels: typo / visu

#386 Fix maj #383
  resources/text/commands/class.json
  resources/text/commands/guildAdd.json
  resources/text/commands/guildShop.json
  resources/text/commands/petNickname.json
  resources/text/commands/shop.json
Labels: typo / visu

#389 refact event translations #277
  resources/text/commands/report.json
  resources/text/events/0.json
  resources/text/events/1.json
  resources/text/events/10.json
  resources/text/events/10000.json
  resources/text/events/100003.json
  resources/text/events/10001.json
  resources/text/events/11.json
  resources/text/events/12.json
  resources/text/events/13.json
  resources/text/events/14.json
  resources/text/events/15.json
  resources/text/events/16.json
  resources/text/events/17.json
  resources/text/events/18.json
  resources/text/events/19.json
  resources/text/events/2.json
  resources/text/events/20.json
  resources/text/events/21.json
  resources/text/events/22.json
  resources/text/events/23.json
  resources/text/events/24.json
  resources/text/events/25.json
  resources/text/events/26.json
  resources/text/events/27.json
  resources/text/events/28.json
  resources/text/events/29.json
  resources/text/events/3.json
  resources/text/events/30.json
  resources/text/events/31.json
  resources/text/events/32.json
  resources/text/events/33.json
  resources/text/events/34.json
  resources/text/events/35.json
  resources/text/events/36.json
  resources/text/events/37.json
  resources/text/events/38.json
  resources/text/events/39.json
  resources/text/events/4.json
  resources/text/events/40.json
  resources/text/events/41.json
  resources/text/events/42.json
  resources/text/events/43.json
  resources/text/events/44.json
  resources/text/events/45.json
  resources/text/events/46.json
  resources/text/events/5.json
  resources/text/events/6.json
  resources/text/events/7.json
  resources/text/events/8.json
  resources/text/events/9.json
  resources/text/events/9999.json
  src/commands/player/ReportCommand.js
  src/core/Database.js
Labels: command, core, enhancement, refactoring

#390 refact messages for female pets in french
  resources/text/commands/petFeed.json
  resources/text/models/pets.json
  src/commands/pets/PetFeedCommand.js
  src/core/Constant.js
  src/core/models/PetEntities.js
Labels: enhancement, refactoring, typo / visu
