Repository Crownicles/Crownicles, pull requests merged in 2021-08, with the labels that each got.

#513 #437 mini event infos aventure
  package.json
  resources/text/smallEvents/botFacts.json
  src/commands/admin/testCommands/Map/MapInfosTestCommand.js
  src/core/Tools.js
  src/core/models/Guilds.js
  src/core/models/MapLocations.js
  src/core/models/PetEntities.js
  src/core/models/Players.js
  src/core/smallEvents/botFactsSmallEvent.js
Labels: event / mini event

#518 Typo + Add new items + New staffMember + invite link
  resources/text/advices.json
  resources/text/armors/54.json
  resources/text/commands/help.json
  resources/text/commands/invite.json
  resources/text/commands/petSell.json
  resources/text/commands/shop.json
  resources/text/events/14.json
  resources/text/events/22.json
  resources/text/events/30.json
  resources/text/events/33.json
  resources/text/events/35.json
  resources/text/events/43.json
  resources/text/events/46.json
  resources/text/smallEvents/class.json
  resources/text/smallEvents/interactOtherPlayers.json
  resources/text/smallEvents/pet.json
  resources/text/smallEvents/smallBadEvent.json
  resources/text/smallEvents/staffMember.json
  resources/text/weapons/55.json
  resources/text/weapons/81.json
Labels: typo / visu, items

#522 hotfix interactOtherPlayersSmallEvent.js
  src/core/smallEvents/interactOtherPlayersSmallEvent.js
Labels: bug

#527 #526 fix dms
  src/commands/admin/UnblockCommand.js
  src/commands/guild/GuildDailyCommand.js
  src/commands/player/DmNotificationCommand.js
  src/commands/player/HelpCommand.js
Labels: bug, refactoring

#544 #543 Fixed + suppression de code innutil
  src/index.js
Labels: bug

#548 Added pm2 script and config
  package.json
  pm2.config.js
Labels: bug

#545 Mise à jour de la branche 2.2.2
  package.json
  pm2.config.js
  resources/text/potions/43.json
  resources/text/potions/44.json
  resources/text/potions/45.json
  resources/text/potions/46.json
  resources/text/potions/48.json
  resources/text/potions/49.json
  resources/text/potions/50.json
  resources/text/potions/51.json
  resources/text/potions/52.json
  resources/text/potions/53.json
  src/commands/player/DmNotificationCommand.js
  src/index.js
Labels: bug
