Repository Crownicles/Crownicles, pull requests merged in 2021-12, with the labels that each got.

#772 new potions json
  resources/text/commands/fight.json
  resources/text/potions/0.json
  resources/text/potions/1.json
  resources/text/potions/10.json
  resources/text/potions/11.json
  resources/text/potions/12.json
  resources/text/potions/13.json
  resources/text/potions/14.json
  resources/text/potions/15.json
  resources/text/potions/16.json
  resources/text/potions/17.json
  resources/text/potions/18.json
  resources/text/potions/19.json
  resources/text/potions/2.json
  resources/text/potions/20.json
  resources/text/potions/21.json
  resources/text/potions/22.json
  resources/text/potions/23.json
  resources/text/potions/24.json
  resources/text/potions/25.json
  resources/text/potions/26.json
  resources/text/potions/27.json
  resources/text/potions/28.json
  resources/text/potions/29.json
  resources/text/potions/3.json
  resources/text/potions/30.json
  resources/text/potions/31.json
  resources/text/potions/32.json
  resources/text/potions/33.json
  resources/text/potions/34.json
  resources/text/potions/35.json
  resources/text/potions/36.json
  resources/text/potions/37.json
  resources/text/potions/38.json
  resources/text/potions/39.json
  resources/text/potions/4.json
  resources/text/potions/40.json
  resources/text/potions/41.json
  resources/text/potions/42.json
  resources/text/potions/43.json
  resources/text/potions/44.json
  resources/text/potions/45.json
  resources/text/potions/46.json
  resources/text/potions/47.json
  resources/text/potions/48.json
  resources/text/potions/49.json
  resources/text/potions/5.json
  resources/text/potions/50.json
  resources/text/potions/51.json
  resources/text/potions/52.json
  resources/text/potions/53.json
  resources/text/potions/6.json
  resources/text/potions/7.json
  resources/text/potions/8.json
  resources/text/potions/9.json
Labels: bug, enhancement

#784 fix mes conneries sur les sw + fix typo server prefix sur les sw aussi
  resources/text/commands/switch.json
  src/commands/player/SwitchCommand.js
Labels: bug, typo / visu

#780 Ajout disclamer mp #757
  resources/text/bot.json
Labels: enhancement, typo / visu, small feature

#805 Create 59.json
  resources/text/events/59.json
Labels: event / mini event

#814 Fix typo advice.json conseil tw
  resources/text/advices.json
  resources/text/smallEvents/class.json
Labels: typo / visu
