Repository Crownicles/Crownicles, pull requests merged in 2021-07, with the labels that each got.

#479 petits fixs
  package.json
  src/core/Command.js
  yarn.lock
Labels: refactoring

#482 Fixed #477 suppression d'une commande admin useless
  config/app.json.default
  resources/text/commands/tournament.json
  resources/text/error.json
  src/commands/admin/TournamentCommand.js
  src/commands/player/FightCommand.js
  src/core/Constant.js
  src/core/MessageError.js
  src/core/fights/Fight.js
  src/core/fights/Fighter.js
Labels: refactoring

#483 #463 fix mention dans prefix
  resources/text/commands/changePrefix.json
  src/commands/admin/ChangePrefixCommand.js
Labels: bug

#484 Fixed #481
  src/commands/player/FightCommand.js
  src/commands/player/FriendlyFightCommand.js
Labels: bug

#487 Update of the map url
  resources/text/commands/map.json
Labels: bug

#488 Fix typos #422
  resources/text/advices.json
  resources/text/armors/43.json
  resources/text/commands/guildDaily.json
  resources/text/commands/guildShelter.json
  resources/text/events/30.json
  resources/text/events/35.json
  resources/text/events/43.json
  resources/text/events/46.json
  resources/text/potions/9.json
  resources/text/smallEvents/class.json
  resources/text/smallEvents/interactOtherPlayers.json
  resources/text/smallEvents/pet.json
  resources/text/smallEvents/smallBadEvent.json
  resources/text/smallEvents/staffMember.json
  resources/text/smallEvents/winGuildXP.json
  resources/text/smallEvents/winHealth.json
  resources/text/smallEventsIntros.json
Labels: typo / visu

#497 Egaspeed
  src/commands/player/FightCommand.js
  src/core/fights/Fight.js
  src/core/fights/Fighter.js
Labels: balancing, bug, enhancement

#499 #498 done plus correction de quelques typos #422
  resources/text/smallEvents/staffMember.json
Labels: event / mini event, typo / visu

#506 Ajout de conseils
  resources/text/advices.json
Labels: enhancement
