Repository Crownicles/Crownicles, pull requests merged in 2021-03, with the labels that each got.

#343 Fix issue + xp
  resources/text/events/41.json
Labels: event, typo / visu

#347 update events emojis unicode
  resources/text/events/0.json
  resources/text/events/1.json
  resources/text/events/10.json
  resources/text/events/11.json
  resources/text/events/12.json
  resources/text/events/13.json
  resources/text/events/14.json
  resources/text/events/15.json
  resources/text/events/16.json
  resources/text/events/17.json
  resources/text/events/18.json
  resources/text/events/19.json
  resources/text/events/2.json
  resources/text/events/20.json
  resources/text/events/21.json
  resources/text/events/22.json
  resources/text/events/23.json
  resources/text/events/24.json
  resources/text/events/25.json
  resources/text/events/26.json
  resources/text/events/27.json
  resources/text/events/28.json
  resources/text/events/29.json
  resources/text/events/3.json
  resources/text/events/30.json
  resources/text/events/31.json
  resources/text/events/32.json
  resources/text/events/33.json
  resources/text/events/34.json
  resources/text/events/35.json
  resources/text/events/36.json
  resources/text/events/37.json
  resources/text/events/38.json
  resources/text/events/39.json
  resources/text/events/4.json
  resources/text/events/40.json
  resources/text/events/41.json
  resources/text/events/42.json
  resources/text/events/43.json
  resources/text/events/44.json
  resources/text/events/45.json
  resources/text/events/46.json
  resources/text/events/5.json
  resources/text/events/6.json
  resources/text/events/7.json
  resources/text/events/8.json
  resources/text/events/9.json
  resources/text/events/9999.json
Labels: event, refactoring

#361 Fix issue 358
  resources/text/commands/idea.json
Labels: obsolete content

#362 Fix issue 357
  resources/text/weapons/67.json
Labels: items, obsolete content

#363 Add new reward type
  config/app.json.default
  resources/text/commands/guildDaily.json
  src/commands/guild/GuildDailyCommand.js
  src/core/Constant.js
Labels: balancing, enhancement

#364 Add giveMeat feature when a pet is free
  resources/text/commands/petFree.json
  src/commands/pets/PetFreeCommand.js
Labels: enhancement

#367 2.2.0
  database/migrations/017-dm-notification.sql
  resources/text/bot.json
  resources/text/commands/dmNotification.json
  resources/text/commands/help.json
  resources/text/commands/unblock.json
  resources/text/models/players.json
  src/commands/admin/TestCommand.js
  src/commands/player/DmNotification.js
  src/commands/player/HelpCommand.js
  src/core/Command.js
  src/core/Tools.js
  src/core/models/Players.js
Labels: bug, enhancement
