Repository Crownicles/Crownicles, pull requests merged in 2021-10, with the labels that each got.

#569 small typos dans le readme
  README.md
Labels: github

#613 Show item type in small event shop #564
  resources/text/smallEvents/shop.json
  src/core/smallEvents/shopSmallEvent.js
Labels: enhancement, event / mini event

#615 Fixed and improved top #425
  src/commands/player/ReportCommand.js
  src/commands/player/TopCommand.js
  src/core/Maps.js
Labels: bug, enhancement
