Repository Crownicles/Crownicles, pull requests merged in 2022-10, with the labels that each got.

#1463 fix #1301
  src/core/messages/DraftBotShopMessage.ts
Labels: bug

#1465 fix #1462 #1461
  resources/text/error.json
  src/commands/CommandsManager.ts
  src/commands/player/HelpCommand.ts
Labels: typo / visu

#1464 Fix atravel #1452
  src/core/maps/TravelTime.ts
Labels: bug

#1467 fix #1455
  resources/text/advices.json
Labels: legal

#1473 Docker workflows
  .github/workflows/docker-image-develop.yml
  .github/workflows/docker-image-master.yml
Labels: deployement

#1474 Fix master workflow
  .github/workflows/docker-image-master.yml
Labels: deployement

#1475 Fix commands creation for main shard
  src/commands/CommandsManager.ts
  src/core/bot/DraftBot.ts
Labels: bug, command

#1500 Fix timewarp logs
  src/core/maps/TravelTime.ts
Labels: bug

#1510 hotfix IOP
  src/core/database/game/models/MapLocation.ts
  src/core/smallEvents/interactOtherPlayersSmallEvent.ts
Labels: bug

#1526 smallEvent textual corrections
  resources/text/smallEvents/advanceTime.json
  resources/text/smallEvents/bigBadEvent.json
  resources/text/smallEvents/botFacts.json
  resources/text/smallEvents/botVote.json
  resources/text/smallEvents/class.json
  resources/text/smallEvents/doNothing.json
  resources/text/smallEvents/findItem.json
  resources/text/smallEvents/findMission.json
  resources/text/smallEvents/findPet.json
  resources/text/smallEvents/findPotions.json
  resources/text/smallEvents/gobletsGame.json
  resources/text/smallEvents/interactOtherPlayers.json
  resources/text/smallEvents/lottery.json
  resources/text/smallEvents/pet.json
  resources/text/smallEvents/shop.json
  resources/text/smallEvents/smallBadEvent.json
  resources/text/smallEvents/space.json
  resources/text/smallEvents/staffMember.json
  resources/text/smallEvents/ultimateFoodMerchant.json
  resources/text/smallEvents/winGuildXP.json
  resources/text/smallEvents/winHealth.json
  resources/text/smallEvents/winPersonalXP.json
Labels: typo / visu, event / mini event

#1529 fix #1514
  resources/text/smallEvents/gobletsGame.json
  src/core/Constants.ts
  src/core/database/game/models/Player.ts
  src/core/smallEvents/interactOtherPlayersSmallEvent.ts
Labels: bug, refactoring

#1535 Fix game migration 003
  src/core/database/game/migrations/003-remove-entity.ts
Labels: bug

#1534 équilibrage argent du roi #1533
  src/core/Constants.ts
Labels: balancing

#1539 Vbump + refacto
  package.json
  src/core/database/logs/LogsReadRequests.ts
Labels: balancing

#1540 Campaign 51 to 53 #1519
  resources/text/campaign.json
  resources/text/events/30.json
  resources/text/events/33.json
  resources/text/missions/bigFeast.json
  resources/text/missions/kingsMoneyValue.json
  resources/text/missions/unlock.json
  src/commands/mission/MissionShopCommand.ts
  src/commands/player/UnlockCommand.ts
  src/core/missions/interfaces/bigFeast.ts
Labels: big feature

#1541 hotfix #1292
  resources/text/error.json
  src/commands/player/ReportCommand.ts
  src/core/utils/BlockingUtils.ts
Labels: bug

#1543 package.json update
  package.json
  src/commands/CommandsManager.ts
  src/commands/SlashCommandBuilderGenerator.ts
  yarn.lock
Labels: dependencies

#1557 Fix #1556
  src/core/smallEvents/petSmallEvent.ts
Labels: bug

#1559 fix 1470
  src/commands/admin/testCommands/Player/skipTutorialTestCommand.ts
Labels: typo / visu, small feature
