Repository Crownicles/Crownicles, pull requests merged in 2022-11, with the labels that each got.

#1582 Bugfixes
  src/commands/CommandsManager.ts
  src/commands/admin/testCommands/Map/TravelTestCommand.ts
  src/commands/admin/testCommands/Player/PlayerSuicideTestCommand.ts
  src/commands/admin/testCommands/Player/skipTutorialTestCommand.ts
  src/commands/admin/testCommands/Time/JailPlayerTestCommand.ts
  src/commands/admin/testCommands/Time/PlayerEffectTestCommand.ts
  src/commands/admin/testCommands/Time/RemovePlayerEffectTestCommand.ts
  src/commands/guild/GuildDailyCommand.ts
  src/commands/player/ReportCommand.ts
  src/commands/player/RespawnCommand.ts
  src/commands/player/ShopCommand.ts
  src/commands/player/TopCommand.ts
  src/commands/player/UnlockCommand.ts
  src/core/database/game/models/Player.ts
  src/core/maps/Maps.ts
  src/core/maps/TravelTime.ts
  src/core/smallEvents/bigBadEventSmallEvent.ts
  src/core/smallEvents/gobletsGameSmallEvent.ts
  src/core/smallEvents/lotterySmallEvent.ts
  src/core/smallEvents/petSmallEvent.ts
  src/core/smallEvents/smallBadEventSmallEvent.ts
  src/core/utils/ErrorUtils.ts
Labels: bug, refactoring

#1588 fix #1587
  src/core/utils/StringFormatter.ts
Labels: bug

#1594 fix #1593
  src/core/Constants.ts
Labels: balancing

#1601 Fix #1600 & small typo
  resources/text/error.json
  src/commands/player/ReportCommand.ts
  src/core/utils/GuildUtils.ts
Labels: bug, typo / visu

#1616 Fix json use #1432
  resources/text/commands/guildInvite.json
  resources/text/smallEvents/botFacts.json
  src/commands/guild/GuildInviteCommand.ts
  src/core/smallEvents/botFactsSmallEvent.ts
Labels: typo / visu, refactoring

#1620 Fix #1604
  src/commands/admin/UnblockCommand.ts
Labels: bug

#1623 Fix #1591
  src/commands/admin/testCommands/Missions/NewDailyMissionTestCommand.ts
Labels: bug

#1618 Switch options #733
  src/commands/player/SellCommand.ts
  src/commands/player/SwitchCommand.ts
Labels: enhancement, command, small feature

#1638 typos #1576
  resources/text/advices.json
  resources/text/commands/inventory.json
  src/core/maps/TravelTime.ts
  src/core/messages/DraftBotInventoryEmbed.ts
  src/core/smallEvents/interactOtherPlayersSmallEvent.ts
Labels: typo / visu

#1641 fix bug missions havePotions #1560
  src/core/utils/ItemUtils.ts
Labels: bug

#1645 fix command top #1644
  src/core/database/game/models/Player.ts
Labels: bug

#1647 fix another bug missions havePotions #1560
  src/core/fights/fighter/PlayerFighter.ts
  src/core/utils/ItemUtils.ts
Labels: bug
