Repository Crownicles/Crownicles, pull requests merged in 2022-05, with the labels that each got.

#1067 Switch slash command #331
  resources/text/commands/daily.json
  resources/text/commands/switch.json
  src/commands/player/SellCommand.ts
  src/commands/player/SwitchCommand.js
  src/commands/player/SwitchCommand.ts
  src/core/messages/DraftBotListChoiceMessage.ts
Labels: enhancement, command, refactoring

#1122 Fix top week, DBL votes and DMs
  src/core/Command.js
  src/core/DBL.js
  src/core/bot/DraftBot.ts
Labels: bug

#1124 bump des dependances cf #1100 et #1117
  package.json
  yarn.lock
Labels: dependencies
