Repository Crownicles/Crownicles, pull requests merged in 2022-12, with the labels that each got.

#1654 Fix switch with no potions #1652
  src/commands/player/SwitchCommand.ts
Labels: bug

#1658 Fix unlimited reports
  src/commands/player/ReportCommand.ts
  src/core/utils/BlockingUtils.ts
Labels: bug

#1660 fix double message lvl up #1515
  src/core/missions/MissionsController.ts
Labels: bug

#1659 Fix switch with no potions #1657
  src/commands/player/SwitchCommand.ts
Labels: bug

#1656 add notification system when a player arrived in the last minute #1631
  resources/text/commands/report.json
  src/core/Constants.ts
  src/core/bot/DraftBot.ts
  src/core/constants/TimeoutFunctionsConstants.ts
  src/core/fights/FightView.ts
Labels: enhancement

#1671 Fix spam notifications #1631
  resources/text/commands/guildDaily.json
  src/commands/guild/GuildDailyCommand.ts
  src/core/bot/DraftBot.ts
Labels: bug

#1672 Fix oncePer trigger + Christmas event typos
  resources/text/events/64.json
  resources/text/events/65.json
  src/commands/admin/testCommands/Map/PossibleEventsTestCommand.ts
  src/core/database/logs/LogsReadRequests.ts
  src/core/events/BigEventsController.ts
Labels: core, event / mini event

#1675 add verification end travel notification + fix notifications bugs #1673
  src/core/bot/DraftBot.ts
  src/core/maps/TravelTime.ts
  src/core/utils/MessageUtils.ts
Labels: bug
