Repository Crownicles/Crownicles, pull requests merged in 2022-06, with the labels that each got.

#1134 PetFree Command slash command #331
  src/commands/pets/PetFreeCommand.js
  src/commands/pets/PetFreeCommand.ts
  src/core/Constant.js
  src/core/Constants.ts
  src/core/constants/PetFreeConstants.ts
Labels: enhancement, command, refactoring

#1154 Fix #1022
  src/commands/mission/MissionsCommand.ts
Labels: bug

#1152 migrations
  database/migrations/026-fixes-3-0-0.sql
Labels: bug

#1156 fix #1155
  database/migrations/026-fixes-3-0-0.sql
Labels: obsolete content

#1157 1er passage sur les blockings conditions #1074
  config/app.json.default
  resources/text/error.json
  src/commands/CommandsManager.ts
  src/commands/admin/DebugBlockedCommand.ts
  src/commands/admin/UnblockCommand.ts
  src/commands/admin/testCommands/Map/ForceReportTestCommand.js
  src/commands/admin/testCommands/Time/BlockPlayerTestCommand.js
  src/commands/guild/GuildAddCommand.ts
  src/commands/guild/GuildCreateCommand.ts
  src/commands/guild/GuildDailyCommand.ts
  src/commands/guild/GuildDescriptionCommand.ts
  src/commands/guild/GuildElderCommand.ts
  src/commands/guild/GuildElderRemoveCommand.ts
  src/commands/guild/GuildKickCommand.ts
  src/commands/guild/GuildLeaveCommand.ts
  src/commands/guild/GuildShopCommand.ts
  src/commands/mission/MissionShopCommand.ts
  src/commands/pets/PetFeedCommand.ts
  src/commands/pets/PetFreeCommand.ts
  src/commands/pets/PetSellCommand.ts
  src/commands/pets/PetTradeCommand.ts
  src/commands/player/ClassCommand.ts
  src/commands/player/DrinkCommand.ts
  src/commands/player/FightCommand.ts
  src/commands/player/ReportCommand.ts
  src/commands/player/SellCommand.ts
  src/commands/player/ShopCommand.ts
  src/commands/player/SwitchCommand.ts
  src/commands/player/UnlockCommand.ts
  src/core/bot/DraftBotConfig.ts
  src/core/bot/ipc/IPCClient.ts
  src/core/bot/ipc/IPCServer.ts
  src/core/constants/BlockingConstants.ts
  src/core/fights/FightController.ts
  src/core/fights/Fighter.ts
  src/core/messages/DraftBotBroadcastValidationMessage.ts
  src/core/models/Server.ts
  src/core/smallEvents/gobletsGameSmallEvent.ts
  src/core/smallEvents/interactOtherPlayersSmallEvent.ts
  src/core/smallEvents/lotterySmallEvent.ts
  src/core/smallEvents/shopSmallEvent.ts
  src/core/utils/BlockingUtils.ts
  src/core/utils/ErrorUtils.ts
  src/core/utils/ItemUtils.ts
Labels: bug, enhancement, refactoring

#1162 Fix typos #952
  resources/text/advices.json
  resources/text/bot.json
  resources/text/commands/drink.json
  resources/text/commands/guildDescription.json
  resources/text/commands/guildLeave.json
  resources/text/commands/missionShop.json
  resources/text/commands/petSell.json
  resources/text/commands/report.json
  resources/text/events/0.json
  resources/text/events/13.json
  resources/text/events/14.json
  resources/text/events/23.json
  resources/text/events/25.json
  resources/text/events/26.json
  resources/text/events/27.json
  resources/text/events/32.json
  resources/text/events/34.json
  resources/text/events/35.json
  resources/text/events/36.json
  resources/text/events/37.json
  resources/text/events/38.json
  resources/text/events/41.json
  resources/text/events/42.json
  resources/text/events/43.json
  resources/text/events/44.json
  resources/text/events/45.json
  resources/text/events/47.json
  resources/text/events/48.json
  resources/text/events/49.json
  resources/text/events/51.json
  resources/text/events/58.json
  resources/text/events/60.json
  resources/text/maplocations/10.json
  resources/text/maplocations/11.json
  resources/text/maplocations/12.json
  resources/text/maplocations/13.json
  resources/text/maplocations/15.json
  resources/text/maplocations/19.json
  resources/text/maplocations/21.json
  resources/text/maplocations/22.json
  resources/text/maplocations/23.json
  resources/text/maplocations/24.json
  resources/text/maplocations/29.json
  resources/text/smallEvents/advanceTime.json
  resources/text/smallEvents/bigBadEvent.json
  resources/text/smallEvents/botFacts.json
  resources/text/smallEvents/class.json
  resources/text/smallEvents/findPet.json
  resources/text/smallEvents/gobletsGame.json
  resources/text/smallEvents/interactOtherPlayers.json
  resources/text/smallEvents/shop.json
  resources/text/smallEvents/smallBadEvent.json
  resources/text/smallEvents/space.json
  resources/text/smallEvents/staffMember.json
  resources/text/smallEvents/ultimateFoodMerchant.json
  resources/text/smallEvents/winGuildXP.json
  resources/text/smallEvents/winHealth.json
  resources/text/smallEvents/winPersonalXP.json
  src/core/smallEvents/interactOtherPlayersSmallEvent.ts
Labels: typo / visu, event / mini event

#1163 Refactor errors & fix #1073
  resources/text/error.json
  src/commands/CommandsManager.ts
  src/commands/admin/ChangeGuildChiefCommand.ts
  src/commands/admin/ChangeMoneyCommand.ts
  src/commands/admin/ChangePointsCommand.ts
  src/commands/admin/ChangePointsWeekCommand.ts
  src/commands/admin/GiveCommand.ts
  src/commands/admin/SendLogsCommand.ts
  src/commands/admin/SendPrivateMessageCommand.ts
  src/commands/guild/GuildAddCommand.ts
  src/commands/guild/GuildCommand.ts
  src/commands/guild/GuildCreateCommand.ts
  src/commands/guild/GuildDailyCommand.ts
  src/commands/guild/GuildDescriptionCommand.ts
  src/commands/guild/GuildElderCommand.ts
  src/commands/guild/GuildElderRemoveCommand.ts
  src/commands/guild/GuildKickCommand.ts
  src/commands/guild/GuildLeaveCommand.ts
  src/commands/guild/GuildShopCommand.ts
  src/commands/mission/MissionShopCommand.ts
  src/commands/mission/MissionsCommand.ts
  src/commands/pets/PetCommand.ts
  src/commands/pets/PetFeedCommand.ts
  src/commands/pets/PetFreeCommand.ts
  src/commands/pets/PetNicknameCommand.ts
  src/commands/pets/PetSellCommand.ts
  src/commands/pets/PetTradeCommand.ts
  src/commands/pets/PetTransferCommand.ts
  src/commands/player/ClassCommand.ts
  src/commands/player/DailyCommand.ts
  src/commands/player/DmNotificationCommand.ts
  src/commands/player/DrinkCommand.ts
  src/commands/player/FightCommand.ts
  src/commands/player/MapCommand.ts
  src/commands/player/ReportCommand.ts
  src/commands/player/RespawnCommand.ts
  src/commands/player/SellCommand.ts
  src/commands/player/ShopCommand.ts
  src/commands/player/SwitchCommand.ts
  src/commands/player/UnlockCommand.ts
  src/core/CommandsTest.ts
  src/core/messages/DraftBotBroadcastValidationMessage.ts
  src/core/messages/DraftBotErrorEmbed.ts
  src/core/messages/DraftBotShopMessage.ts
  src/core/smallEvents/findPetSmallEvent.ts
  src/core/smallEvents/petSmallEvent.ts
  src/core/smallEvents/shopSmallEvent.ts
  src/core/smallEvents/ultimateFoodMerchantSmallEvent.ts
  src/core/utils/BlockingUtils.ts
  src/core/utils/ErrorUtils.ts
  src/core/utils/GuildUtils.ts
Labels: bug, enhancement, refactoring

#1167 #965 plus de bloquage pour la commande map
  src/commands/player/MapCommand.ts
Labels: enhancement, command

#1170 Add use of special maps in an event (enchancement of #965)
  src/commands/player/MapCommand.ts
  src/core/models/Entity.ts
Labels: enhancement, command, small feature
