Repository Crownicles/Crownicles, pull requests merged in 2022-07, with the labels that each got.

#1184 Petitsfixsdivers
  resources/text/advices.json
  resources/text/classes/0.json
  resources/text/classes/12.json
  resources/text/classes/4.json
  resources/text/classes/8.json
  resources/text/smallEvents/advanceTime.json
Labels: typo / visu, balancing

#1185 translations checkup
  resources/text/commands/guildDaily.json
  resources/text/commands/profile.json
  resources/text/commands/top.json
  resources/text/smallEvents/bigBadEvent.json
  resources/text/smallEvents/staffMember.json
Labels: typo / visu

#1191 Typos symsym #1183
  resources/text/bot.json
  resources/text/smallEvents/advanceTime.json
  resources/text/smallEvents/bigBadEvent.json
  resources/text/smallEvents/botFacts.json
  resources/text/smallEvents/botVote.json
  resources/text/smallEvents/class.json
  resources/text/smallEvents/doNothing.json
  resources/text/smallEvents/findItem.json
  resources/text/smallEvents/findMission.json
  resources/text/smallEvents/findPet.json
  resources/text/smallEvents/findPotions.json
  resources/text/smallEvents/gobletsGame.json
  resources/text/smallEvents/interactOtherPlayers.json
  resources/text/smallEvents/lottery.json
  resources/text/smallEvents/pet.json
  resources/text/smallEvents/shop.json
  resources/text/smallEvents/smallBadEvent.json
  resources/text/smallEvents/staffMember.json
  resources/text/smallEvents/ultimateFoodMerchant.json
  resources/text/smallEvents/winGuildXP.json
  resources/text/smallEvents/winHealth.json
  resources/text/smallEvents/winPersonalXP.json
  src/commands/player/ReportCommand.ts
Labels: typo / visu

#1186 Polishing mission descriptions
  resources/text/missions/chooseClass.json
  resources/text/missions/commandMission.json
  resources/text/missions/commandReport.json
  resources/text/missions/drinkAlcohol.json
  resources/text/missions/drinkPotionRarity.json
  resources/text/missions/earnPoints.json
  resources/text/missions/earnXP.json
  resources/text/missions/exploreDifferentPlaces.json
  resources/text/missions/goToPlace.json
  resources/text/missions/guildDaily.json
  resources/text/missions/haveItemRarity.json
  resources/text/missions/meetDifferentPlayers.json
  resources/text/missions/reachScore.json
  src/core/missions/interfaces/fightAttacks.ts
Labels: enhancement, core, typo / visu

#1187 Refactors for #1057
  src/commands/mission/MissionsCommand.ts
  src/core/messages/DraftBotEmbed.ts
  src/core/messages/DraftBotMissionsMessage.ts
Labels: typo / visu, refactoring

#1212 Fix guild chief leave #1210
  src/commands/guild/GuildLeaveCommand.ts
Labels: bug

#1223 Fix crash when MP closed #1218
  src/core/utils/MessageUtils.ts
Labels: bug

#1221 Fix nerf #1215
  src/core/models/Entity.ts
  src/core/models/ObjectItem.ts
Labels: bug, typo / visu

#1224 1197 rajouter les traductions anglaises des fights
  resources/text/commands/class.json
  resources/text/commands/fight.json
Labels: typo / visu

#1229 Fix missions xp overlapping #1216
  src/core/missions/MissionsController.ts
  src/core/models/Player.ts
Labels: bug

#1231 Removed old code
  src/commands/admin/GiveCommand.ts
  src/core/Command.js
  src/core/Constant.js
  src/core/Tools.js
  src/core/utils/StringUtils.ts
Labels: refactoring

#1232 Last typos/fixes
  resources/text/commands/guildInventory.json
  resources/text/commands/guildStorage.json
  resources/text/events/49.json
  resources/text/events/51.json
  resources/text/events/60.json
  resources/text/events/61.json
  resources/text/smallEvents/class.json
  src/core/missions/MissionsController.ts
Labels: bug, typo / visu

#1233 Fix help & suppress useless json
  resources/text/commands/changePrefix.json
  resources/text/commands/help.json
  src/core/constants/HelpConstants.ts
Labels: typo / visu

#1235 Mergemasterpremaj
  src/commands/CommandsManager.ts
  src/commands/guild/GuildCommand.ts
  src/core/DBL.js
  src/core/bot/DraftBot.ts
Labels: bug

#1261 Fixes post update
  resources/text/error.json
  src/commands/mission/MissionShopCommand.ts
  src/commands/pets/PetCommand.ts
  src/commands/player/ReportCommand.ts
  src/commands/player/SellCommand.ts
  src/core/constants/BlockingConstants.ts
  src/core/missions/MissionsController.ts
  src/core/models/PlayerMissionsInfo.ts
  src/core/smallEvents/gobletsGameSmallEvent.ts
  src/core/smallEvents/interactOtherPlayersSmallEvent.ts
Labels: bug, typo / visu

#1262 fix #1245
  database/migrations/027-bugged-missions.sql
  src/core/fights/FightController.ts
Labels: bug

#1263 fix #1248
  src/commands/player/FightCommand.ts
  src/commands/player/ReportCommand.ts
Labels: bug

#1264 Fixes post maj
  resources/text/commands/classInfo.json
  resources/text/events/63.json
  resources/text/fightactions/intenseAttack.json
  resources/text/missions/earnPoints.json
  resources/text/missions/reachScore.json
  resources/text/smallEvents/gobletsGame.json
  src/commands/guild/GuildCommand.ts
  src/commands/player/ReportCommand.ts
  src/commands/player/SwitchCommand.ts
  src/core/fights/FightController.ts
Labels: bug

#1293 Update FUNDING.yml
  .github/FUNDING.yml
Labels: github
