Repository Crownicles/Crownicles, pull requests merged in 2022-02, with the labels that each got.

#876 fix #875 & #811
  resources/text/commands/fight.json
  resources/text/pets/41.json
  resources/text/pets/54.json
  src/core/fights/Fight.js
  src/core/smallEvents/lotterySmallEvent.js
Labels: bug, typo / visu

#901 JUSQUE fix #153
  resources/text/maplocations/1.json
  resources/text/maplocations/10.json
  resources/text/maplocations/11.json
  resources/text/maplocations/12.json
  resources/text/maplocations/13.json
  resources/text/maplocations/14.json
  resources/text/maplocations/15.json
  resources/text/maplocations/16.json
  resources/text/maplocations/17.json
  resources/text/maplocations/18.json
  resources/text/maplocations/19.json
  resources/text/maplocations/2.json
  resources/text/maplocations/20.json
  resources/text/maplocations/21.json
  resources/text/maplocations/22.json
  resources/text/maplocations/23.json
  resources/text/maplocations/24.json
  resources/text/maplocations/25.json
  resources/text/maplocations/26.json
  resources/text/maplocations/27.json
  resources/text/maplocations/3.json
  resources/text/maplocations/4.json
  resources/text/maplocations/5.json
  resources/text/maplocations/6.json
  resources/text/maplocations/7.json
  resources/text/maplocations/8.json
  resources/text/maplocations/9.json
  resources/text/missions/goToPlace.json
  src/core/missions/interfaces/goToPlace.ts
  src/core/models/MapLocation.ts
Labels: typo / visu

#905 Send all dm from bot's dm with the id linked (userID)
  config/app.json.default
  src/core/Command.js
Labels: enhancement, small feature

#823 première version contributing guidelines
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: github

#917 equilibrage #916
  resources/text/objects/1.json
  resources/text/objects/11.json
  resources/text/objects/27.json
  resources/text/objects/35.json
  resources/text/objects/40.json
  resources/text/objects/43.json
  resources/text/objects/45.json
  resources/text/weapons/80.json
Labels: balancing

#948 Fixes before majs
  resources/text/commands/guildAdd.json
  resources/text/commands/guildDescription.json
  resources/text/commands/guildElder.json
  resources/text/commands/guildElderRemove.json
  resources/text/commands/guildKick.json
  resources/text/commands/help.json
  resources/text/error.json
  resources/text/models/missions.json
  src/commands/guild/GuildAddCommand.js
  src/commands/mission/MissionShopCommand.ts
  src/commands/mission/MissionsCommand.ts
  src/commands/player/ClassCommand.js
  src/commands/player/DmNotificationCommand.js
  src/commands/player/DrinkCommand.js
  src/commands/player/MapCommand.js
  src/commands/player/ReportCommand.js
  src/commands/player/UnlockCommand.js
Labels: bug, typo / visu
