Repository Crownicles/Crownicles, pull requests merged in 2022-09, with the labels that each got.

#1390 fix compatibility between linux and windows
  src/core/database/Database.ts
Labels: bug

#1393 Fixbugmajeur
  src/core/fightActions/FightActionController.ts
Labels: refactoring

#1392 intent clarification #1385
  src/core/bot/index.ts
  src/core/intents.ts
Labels: refactoring, small feature

#1402 delete obsolete backup system #1166
  .gitignore
  config/config.default.toml
  src/core/Constants.ts
  src/core/backup/DraftBotBackup.ts
  src/core/backup/DropboxBackup.ts
  src/core/backup/LocalBackup.ts
  src/core/bot/DraftBot.ts
  src/core/bot/DraftBotConfig.ts
  src/core/bot/index.ts
Labels: bug, enhancement, core, refactoring

#1405 Update README.md for docker #1398
  README.md
Labels: github

#1414 Fix logs database findOrCreate transactions #1400
  src/core/database/logs/LogsDatabase.ts
Labels: bug

#1409 petits fixs divers, typo et refactoring
  .eslintignore
  README.md
  resources/text/commands/help.json
  src/core/bot/ipc/IPCClient.ts
  src/core/database/logs/LogsDatabase.ts
  src/core/fightActions/interfaces/viciousAttack.ts
  src/core/fights/FightView.ts
  src/core/messages/DraftBotBroadcastValidationMessage.ts
  src/core/messages/DraftBotReactionMessage.ts
  src/core/messages/DraftBotShopMessage.ts
  src/core/messages/DraftBotVoteMessage.ts
  src/core/missions/IMission.ts
  src/core/missions/MissionsController.ts
Labels: typo / visu, refactoring

#1417 Multiple actions in 1 test command Pog
  src/commands/admin/TestCommand.ts
  src/core/CommandsTest.ts
Labels: enhancement, command

#1422 Hotfix sql requests
  src/core/database/game/models/Armor.ts
  src/core/database/game/models/Entity.ts
  src/core/database/game/models/MapLocation.ts
  src/core/database/game/models/ObjectItem.ts
  src/core/database/game/models/Potion.ts
  src/core/database/game/models/Tag.ts
  src/core/database/game/models/Weapon.ts
Labels: bug

#1421 Fix emoji detection (so effect & givebadgetest command too) #1411
  src/commands/admin/testCommands/Time/PlayerEffectTestCommand.ts
  src/core/utils/StringUtils.ts
Labels: bug

#1425 Log the whole error and not just the stack
  src/core/bot/index.ts
  src/index.ts
Labels: refactoring

#1423 Fix /test smallEvent description
  src/commands/admin/testCommands/Map/SmallEventTestCommand.ts
Labels: bug

#1424 Fix #1383
  resources/text/smallEvents/interactOtherPlayers.json
Labels: bug

#1437 Petitesameliorations
  .github/ISSUE_TEMPLATE/bug_report.yml
  resources/text/commands/ping.json
Labels: enhancement, github

#1441 Add de nouveaux items #1318
  resources/text/objects/44.json
  resources/text/objects/46.json
  resources/text/objects/47.json
  resources/text/objects/48.json
  resources/text/objects/65.json
  resources/text/objects/67.json
  resources/text/objects/68.json
  resources/text/potions/56.json
  resources/text/weapons/86.json
  resources/text/weapons/87.json
  resources/text/weapons/88.json
Labels: items / new pet
