Repository Crownicles/Crownicles, pull requests merged in 2023-11, with the labels that each got.

#2268 Fix missing expiration time #2266
  resources/text/missions/spendMoney.json
Labels: bug

#2265 Add Read History Message permission check
  resources/text/bot.json
  src/commands/CommandsManager.ts
Labels: bug

#2281 Fix #2279
  src/core/fights/FightController.ts
Labels: bug

#2286 New staff member in small event #2278
  resources/text/smallEvents/staffMember.json
Labels: small feature

#2283 Fix #2282
  src/core/fights/FightController.ts
Labels: bug

#2285 ajout évent 'arnaque tigres' à la Route des Merveilles
  resources/text/events/73.json
Labels: event / mini event

#2296 Fix #2290
  src/commands/player/ProfileCommand.ts
Labels: bug

#2301 Fix #2300
  resources/text/smallEvents/interactOtherPlayers.json
Labels: bug, typo / visu

#2308 NEO API change #2306
  src/core/utils/SpaceUtils.ts
Labels: bug

#2314 fix #2302
  src/core/smallEvents/cartSmallEvent.ts
Labels: bug

#2315 fix #2288
  resources/text/events/73.json
Labels: event / mini event, balancing

#2321 fix #2319
  src/core/events/PossibilityOutcome.ts
Labels: bug

#2316 Update tiger event with Procion and Ravenclaw's comments and modifica…
  resources/text/events/73.json
Labels: event / mini event
