Repository Crownicles/Crownicles, pull requests merged in 2023-10, with the labels that each got.

#2180 Fix bug notifications #2177
  src/core/utils/MessageUtils.ts
Labels: bug

#2189 3 nouveaux évents
  resources/text/events/70.json
  resources/text/events/71.json
  resources/text/events/72.json
Labels: event / mini event

#2191 Smallfixesevents
  resources/text/error.json
  resources/text/events/70.json
  resources/text/events/71.json
  resources/text/events/72.json
  src/core/constants/EffectsConstants.ts
Labels: event / mini event, balancing

#2199 Fix respawn bug #2198
  src/commands/player/RespawnCommand.ts
Labels: bug

#2210 fix: migration functions uses database name
  src/core/database/game/GameDatabaseUtils.ts
Labels: bug, not end user

#2212 fix: turbo micro fix pour ceux à la mauvaise mission lors de la migration
  src/core/database/game/GameDatabaseUtils.ts
Labels: bug

#2213 prefix: hardcoding the initial blob size to avoid problems with unmat…
  src/core/database/game/migrations/017-campaignBlob.ts
Labels: bug

#2223 english maps #2128
  src/commands/player/MapCommand.ts
Labels: typo / visu, small feature

#2226 Update bug_report.yml #2054
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: github

#2227 small fix missions
  resources/text/missions/gainRage.json
  resources/text/missions/spendMoney.json
  resources/text/missions/winBoss.json
  src/commands/admin/testCommands/Global action/MigrationTestCommand.ts
Labels: bug

#2234 fix: inexisting drinkEnergyPotion mission
  resources/text/campaign.json
  resources/text/missions/drinkEnergyPotion.json
  src/core/utils/ItemUtils.ts
Labels: bug

#2246 refactor: format getting formatted to avoid overformatting the formatter with useless format
  src/commands/CommandsManager.ts
  src/commands/admin/ResetBadgesCommand.ts
  src/commands/guild/GuildElderCommand.ts
  src/commands/guild/GuildElderRemoveCommand.ts
  src/commands/guild/GuildInviteCommand.ts
  src/commands/pets/PetSellCommand.ts
  src/commands/pets/PetTransferCommand.ts
  src/commands/player/ClassInfoCommand.ts
  src/commands/player/HelpCommand.ts
  src/commands/player/ReportCommand.ts
  src/commands/player/ShopCommand.ts
  src/core/Translations.ts
  src/core/database/game/models/Player.ts
  src/core/smallEvents/boatAdviceSmallEvent.ts
  src/core/smallEvents/leagueRewardSmallEvent.ts
  src/core/smallEvents/winEnergySmallEvent.ts
  src/core/utils/BlockingUtils.ts
  src/core/utils/MessageUtils.ts
  src/core/utils/StringFormatter.ts
Labels: refactoring

#2255 improve wording of new small event #1889
  resources/text/smallEvents/epicItemShop.json
Labels: typo / visu, event / mini event

#2258 fix missing issue big bad event #2257
  resources/text/smallEvents/bigBadEvent.json
Labels: bug

#2259 fix double reply on class command #2256
  src/commands/player/ClassCommand.ts
Labels: bug

#2267 Added missing money gain #2266
  resources/text/missions/spendMoney.json
Labels: bug
