Repository Crownicles/Crownicles, pull requests merged in 2023-07, with the labels that each got.

#2021 feat: rage logs #2016
  src/core/constants/LogsConstants.ts
  src/core/database/game/models/Player.ts
  src/core/database/logs/LogsDatabase.ts
  src/core/database/logs/migrations/005-rage-pve-islands.ts
  src/core/database/logs/models/LogsPlayersRage.ts
  src/core/fights/actions/interfaces/players/rageExplosion.ts
  src/core/smallEvents/fightPetSmallEvent.ts
Labels: small feature, not end user

#2027 fix #2025
  src/commands/player/JoinBoatCommand.ts
  src/core/constants/PVEConstants.ts
  src/core/database/game/models/Player.ts
  src/core/smallEvents/goToPVEIslandSmallEvent.ts
Labels: bug

#2033 fix #2031
  src/commands/player/JoinBoatCommand.ts
Labels: bug

#2029 fix #2024
  resources/text/error.json
  src/commands/player/ReportCommand.ts
  src/core/constants/BlockingConstants.ts
  src/core/constants/PVEConstants.ts
Labels: bug

#2035 deleted pet fight action #2032
  src/core/smallEvents/fightPet/FightPetActions.ts
  src/core/smallEvents/fightPetSmallEvent.ts
Labels: bug

#2036 fix #2026
  src/core/bot/DraftBot.ts
Labels: bug

#2044 Fix2014
  src/commands/player/ClassCommand.ts
Labels: bug

#2043 fix #2028
  src/core/smallEvents/witch/WitchEvents.ts
Labels: bug

#2062 Fix#2060
  src/core/constants/PVEConstants.ts
  src/core/database/logs/LogsReadRequests.ts
  src/core/maps/Maps.ts
Labels: enhancement, balancing

#2063 fix #2061 + small balancing #1993
  resources/text/models/players.json
  src/core/constants/PVEConstants.ts
Labels: typo / visu, balancing

#2065 Fix magma titan that takes damages from the sun #2046
  resources/text/commands/fight.json
  src/core/fights/FightWeather.ts
Labels: bug

#2066 Fix guild attack #2060
  src/core/database/logs/LogsReadRequests.ts
  src/core/maps/MapCache.ts
Labels: bug

#2068 small fight balance #2067
  resources/text/commands/help.json
  src/core/fights/actions/interfaces/players/chargingAttack.ts
  src/core/fights/actions/interfaces/players/energeticAttack.ts
  src/core/fights/actions/interfaces/players/heavyAttack.ts
  src/core/fights/actions/interfaces/players/ramAttack.ts
Labels: balancing

#2077 Update packages and node #1999
  Dockerfile
  package.json
  yarn.lock
Labels: dependencies

#2078 Typos
  resources/text/advices.json
  resources/text/commands/report.json
  resources/text/fightactions/cursed.json
  resources/text/models/players.json
  resources/text/smallEvents/winEnergy.json
  resources/text/smallEvents/witch.json
Labels: typo / visu

#2079 downgrade mariadb because of https://github.com/sequelize/sequelize/i…
  package.json
  yarn.lock
Labels: dependencies, balancing

#2080 fix #2075 + petit equilibrage
  resources/text/monsters/forestTroll.json
  resources/text/monsters/rockGolem.json
  src/core/constants/PVEConstants.ts
  src/core/fights/FightController.ts
Labels: balancing

#2093 Fixed allies on pve island and improved guild embed #2092
  resources/text/commands/guild.json
  src/commands/guild/GuildCommand.ts
  src/core/maps/Maps.ts
Labels: bug

#2098 fix: #2097
  src/commands/guild/GuildCommand.ts
Labels: bug
