Repository Crownicles/Crownicles, pull requests merged in 2023-03, with the labels that each got.

#1821 Replace skip mission to change mission #1819
  resources/text/commands/missionShop.json
  src/commands/mission/MissionShopCommand.ts
  src/core/database/game/models/Mission.ts
  src/core/missions/MissionsController.ts
Labels: enhancement, balancing, small feature

#1823 Fix give weeklypoints #1808
  src/core/missions/MissionsController.ts
Labels: bug

#1827 Update des dépendances #1812 #1799 #1794
  package.json
  yarn.lock
Labels: dependencies

#1828 fix #1484
  resources/text/commands/changeLanguage.json
  src/commands/CommandsManager.ts
Labels: bug

#1832 2nd player breath #1829
  resources/text/commands/top.json
  src/core/fights/FightController.ts
  src/core/fights/fighter/Fighter.ts
Labels: balancing

#1834 fix #1833
  src/commands/player/FightCommand.ts
  src/core/database/logs/LogsDatabase.ts
  src/core/database/logs/LogsReadRequests.ts
Labels: bug

#1838 #fix 1835
  resources/text/commands/drink.json
  resources/text/commands/help.json
  resources/text/fightactions/boomerangAttack.json
  resources/text/fightactions/counterAttack.json
  resources/text/fightactions/intenseAttack.json
  resources/text/fightactions/ramAttack.json
Labels: typo / visu

#1840 rankedFight and friendlyFight missions migrations #1839
  src/core/database/game/migrations/009-updateFightMissions.ts
Labels: bug

#1842 fix #1841
  resources/text/smallEvents/leagueReward.json
  src/commands/CommandsManager.ts
Labels: bug

#1844 refactor: registerAllCommands in CommandsManager.ts #1843
  src/commands/CommandsManager.ts
Labels: refactoring

#1849 Fix command skiptuto and display profile without destination #1813
  src/commands/admin/testCommands/Player/skipTutorialTestCommand.ts
  src/commands/player/ProfileCommand.ts
  src/core/database/game/models/Player.ts
Labels: bug

#1862 fix #1861 + version bump
  package.json
  src/core/fights/fighter/PlayerFighter.ts
Labels: bug

#1881 Fix #1880
  src/commands/player/ClassCommand.ts
Labels: bug

#1877 Fix #1876
  src/core/fights/FightController.ts
  src/core/fights/fighter/Fighter.ts
  src/core/fights/fighter/PlayerFighter.ts
Labels: bug

#1892 Add handshake #1890
  src/core/constants/FightConstants.ts
  src/core/fights/FightView.ts
Labels: enhancement

#1893 Update node alpine lines in README
  README.md
Labels: github

#1900 Fix #1899
  src/core/fights/FightController.ts
Labels: bug

#1905 Fix maintenance on different shards #1898
  src/commands/admin/MaintenanceCommand.ts
  src/core/bot/DraftBotWebServer.ts
  src/core/bot/ipc/IPCClient.ts
  src/core/bot/ipc/IPCServer.ts
Labels: bug, deployement
