Repository Crownicles/Crownicles, pull requests merged in 2023-08, with the labels that each got.

#2121 added tips github action
  .github/workflows/dailyAdvice.yml
Labels: enhancement

#2122 Update dailyAdvice.yml
  .github/workflows/dailyAdvice.yml
Labels: enhancement

#2127 more work on #2103
  .github/workflows/dailyAdvice.yml
Labels: enhancement, small feature

#2131 Fix fight blocking on PVE island #2113
  resources/text/commands/fight.json
  src/commands/player/FightCommand.ts
  src/core/constants/FightConstants.ts
Labels: bug

#2133 Optimisation Dockerfile
  Dockerfile
  package.json
Labels: deployement

#2141 fix Docker build bug
  Dockerfile
  package.json
Labels: bug, dependencies, deployement

#2144 Fix Docker
  Dockerfile
  package.json
Labels: bug, dependencies, deployement

#2153 rework useplayerpet #2149
  resources/text/smallEvents/doNothing.json
  src/core/constants/SmallEventConstants.ts
  src/core/smallEvents/fightPet/interfaces/usePlayerPet.ts
Labels: bug, balancing
