Repository Crownicles/Crownicles, pull requests merged in 2023-01, with the labels that each got.

#1711 Fix #1663
  src/core/smallEvents/witchSmallEvent.ts
  src/core/utils/ItemUtils.ts
  src/core/witch/WitchEvent.ts
  src/core/witch/interfaces/distiller.ts
Labels: bug

#1710 Fix #1674
  src/core/events/PossibilityOutcome.ts
Labels: bug

#1713 1701 bug cohrence disparue
  resources/text/events/11.json
  src/core/events/PossibilityOutcome.ts
Labels: bug

#1712 Fix #1700
  src/commands/player/ReportCommand.ts
Labels: bug

#1714 Fix #1650
  src/core/smallEvents/lotterySmallEvent.ts
Labels: bug

#1716 fix #1702
  resources/text/events/41.json
Labels: bug

#1718 1688fix
  resources/text/commands/fight.json
  resources/text/commands/petSell.json
  src/commands/pets/PetSellCommand.ts
  src/commands/player/FightCommand.ts
  src/core/constants/FightConstants.ts
Labels: bug

#1724 Typos #1640
  resources/text/advices.json
  resources/text/bot.json
  resources/text/commands/drink.json
  resources/text/commands/fight.json
  resources/text/events/44.json
  resources/text/events/52.json
  resources/text/events/63.json
  resources/text/fightactions/benediction.json
  resources/text/items.json
  resources/text/maplocations/23.json
  resources/text/missions/fightStreak.json
  resources/text/models/players.json
  resources/text/smallEvents/interactOtherPlayers.json
  resources/text/smallEvents/smallBadEvent.json
  resources/text/smallEvents/space.json
  resources/text/smallEvents/staffMember.json
  resources/text/smallEvents/witch.json
  resources/text/weapons/7.json
  src/commands/admin/testCommands/Player/skipTutorialTestCommand.ts
  src/commands/player/ReportCommand.ts
  src/core/database/game/models/Player.ts
Labels: typo / visu

#1725 Fix
  src/core/fights/FightController.ts
  yarn.lock
Labels: dependencies

#1728 suppression de l'attaque mutation et ajout de la dark attack #1715
  resources/text/classes/24.json
  resources/text/fightactions/darkAttack.json
  resources/text/fightactions/mutationAttack.json
  src/core/constants/FightConstants.ts
  src/core/fights/actions/interfaces/darkAttack.ts
  src/core/fights/actions/interfaces/mutationAttack.ts
Labels: bug, enhancement

#1733 Fix notification during report
  src/commands/player/RespawnCommand.ts
Labels: bug

#1693 Fix multi message between shards #1690
  src/commands/CommandsManager.ts
  src/core/utils/MessageUtils.ts
Labels: bug

#1741 Fix permission problem in thread #1705
  src/commands/CommandsManager.ts
Labels: bug

#1740 Fix format bug in dm help #1738
  src/commands/CommandsManager.ts
Labels: bug

#1739 Fix experience bug #1721
  src/core/missions/MissionsController.ts
Labels: bug

#1744 added the breath needed to perform an attack in the classInfo menu #1737
  src/commands/player/ClassInfoCommand.ts
Labels: typo / visu

#1745 Fix experience bug when get an item #1742
  src/core/events/PossibilityOutcome.ts
Labels: bug

#1743 Fix experience bug with missions complete #1721
  src/core/missions/MissionsController.ts
Labels: bug

#1752 Fix duplicate mission #1721
  src/commands/guild/GuildDailyCommand.ts
  src/core/database/game/models/Player.ts
  src/core/missions/MissionsController.ts
Labels: bug
