Repository Crownicles/Crownicles, pull requests merged in 2023-06, with the labels that each got.

#1976 PVE logs #1765
  resources/text/commands/fight.json
  src/commands/admin/testCommands/Guild/GuildScoreTestCommand.ts
  src/commands/player/FightCommand.ts
  src/commands/player/ReportCommand.ts
  src/core/database/game/models/Guild.ts
  src/core/database/logs/LogsDatabase.ts
  src/core/database/logs/migrations/004-pve.ts
  src/core/database/logs/models/LogsGuildsPoints.ts
  src/core/database/logs/models/LogsPveFightsActionsUsed.ts
  src/core/database/logs/models/LogsPveFightsResults.ts
  src/core/fights/FightController.ts
  src/core/fights/FightView.ts
  src/core/fights/FightWeather.ts
  src/core/fights/actions/interfaces/monsters/eruptionAttack.ts
  src/core/fights/fighter/Fighter.ts
  src/core/fights/fighter/MonsterFighter.ts
  src/core/smallEvents/bonusGuildPVEIslandSmallEvent.ts
Labels: enhancement

#1979 Pve fixes
  resources/text/commands/fight.json
  src/commands/player/ReportCommand.ts
  src/core/fights/FightController.ts
  src/core/fights/FightWeather.ts
  src/core/fights/fighter/PlayerFighter.ts
  src/core/smallEvents/leagueRewardSmallEvent.ts
Labels: bug

#1990 fix #1989
  src/core/database/game/migrations/013-settings.ts
Labels: bug

#1992 female animals are now correct #1991
  resources/text/pets/16.json
  resources/text/pets/23.json
  resources/text/pets/24.json
  resources/text/pets/25.json
  resources/text/pets/30.json
  resources/text/pets/32.json
  resources/text/pets/35.json
  resources/text/pets/36.json
  resources/text/pets/37.json
  resources/text/pets/39.json
  resources/text/pets/41.json
  resources/text/pets/44.json
  resources/text/pets/47.json
  resources/text/pets/49.json
  resources/text/pets/5.json
  resources/text/pets/60.json
  resources/text/pets/70.json
  resources/text/pets/71.json
Labels: typo / visu

#2003 refact: deepsource fixes
  src/commands/CommandsManager.ts
  src/commands/admin/ChangeMoneyCommand.ts
  src/commands/admin/ChangePointsCommand.ts
  src/commands/admin/ListItemsCommand.ts
  src/commands/admin/ServersCommand.ts
  src/commands/admin/testCommands/Guild/GuildXpTestCommand.ts
  src/commands/admin/testCommands/Guild/SetFoodTestCommand.ts
  src/commands/admin/testCommands/Map/MapInfosTestCommand.ts
  src/commands/admin/testCommands/Missions/DebugMissionsTestCommand.ts
  src/commands/admin/testCommands/Pet/PetTestCommand.ts
  src/commands/admin/testCommands/Player/ExperienceTestCommand.ts
  src/commands/admin/testCommands/Time/PlayerEffectTestCommand.ts
  src/commands/guild/GuildShopCommand.ts
  src/commands/guild/GuildStorageCommand.ts
  src/commands/player/ClassCommand.ts
  src/commands/player/FightCommand.ts
  src/commands/player/HelpCommand.ts
  src/commands/player/PingCommand.ts
  src/commands/player/ProfileCommand.ts
  src/commands/player/ReportCommand.ts
  src/commands/player/UnlockCommand.ts
  src/core/DBL.ts
  src/core/bot/DraftBot.ts
  src/core/bot/DraftBotConfig.ts
  src/core/bot/index.ts
  src/core/bot/ipc/IPCClient.ts
  src/core/bot/ipc/IPCServer.ts
  src/core/database/game/GameDatabase.ts
  src/core/database/game/models/Class.ts
  src/core/database/game/models/MainItemModel.ts
  src/core/database/game/models/MapLocation.ts
  src/core/database/game/models/PetEntity.ts
  src/core/database/game/models/Player.ts
  src/core/database/game/models/SupportItemModel.ts
  src/core/database/game/models/Tag.ts
  src/core/database/logs/LogsDatabase.ts
  src/core/events/BigEventTrigger.ts
  src/core/events/PossibilityOutcome.ts
  src/core/fights/FightController.ts
  src/core/fights/FightView.ts
  src/core/fights/actions/interfaces/players/simpleAttack.ts
  src/core/fights/fighter/Fighter.ts
  src/core/messages/DraftBotShopMessage.ts
  src/core/messages/DraftBotValidateReactionMessage.ts
  src/core/messages/DraftBotVoteMessage.ts
  src/core/missions/MissionsController.ts
  src/core/smallEvents/bigBadEventSmallEvent.ts
  src/core/smallEvents/findMissionSmallEvent.ts
  src/core/smallEvents/goToPVEIslandSmallEvent.ts
  src/core/smallEvents/interactOtherPlayersSmallEvent.ts
  src/core/smallEvents/petSmallEvent.ts
  src/core/utils/BotUtils.ts
  src/core/utils/ItemUtils.ts
  src/core/utils/StringUtils.ts
  src/core/utils/astronomy.ts
Labels: refactoring
