Repository Crownicles/Crownicles, pull requests merged in 2024-10, with the labels that each got.

#2592 update discord js #2591
  Discord/package.json
  Discord/src/commands/CommandsManager.ts
  Discord/yarn.lock
Labels: dependencies

#2603 space fix i18n
  Discord/src/packetHandlers/handlers/SmallEventsHandler.ts
  Lang/fr/smallEvents.json
Labels: refactoring

#2621 findItem core + front
  Core/src/core/smallEvents/findItem.ts
  Discord/src/packetHandlers/handlers/SmallEventsHandler.ts
  Lang/fr/smallEvents.json
  Lib/src/packets/smallEvents/SmallEventFindItemPacket.ts
Labels: event / mini event

#2622 fix inventory
  Core/src/commands/player/InventoryCommand.ts
  Core/src/data/MainItem.ts
  Core/src/data/ObjectItem.ts
  Discord/src/utils/DisplayUtils.ts
Labels: bug

#2630 Fix issue with keycloak gameUsername attribute #2434
  Discord/src/commands/player/InventoryCommand.ts
  Discord/src/commands/player/ProfileCommand.ts
  Lib/src/keycloak/KeycloakUser.ts
  Lib/src/keycloak/KeycloakUtils.ts
Labels: bug
