Repository Crownicles/Crownicles, pull requests merged in 2024-02, with the labels that each got.

#2379 Fix #2378
  src/commands/CommandsManager.ts
Labels: bug

#2413 Eslintupdate
  Core/.eslintrc.json
  Discord/.eslintrc.json
  Lib/.eslintrc.json
Labels: refactoring

#2419 Invite command #2273
  Discord/src/commands/player/InviteCommand.ts
  Lang/en/commands.json
  Lang/en/discordBuilder.json
  Lang/fr/commands.json
  Lang/fr/discordBuilder.json
Labels: command, refactoring

#2424 update node #2423
  Core/package.json
  Discord/package.json
Labels: bug
