Repository Crownicles/Crownicles, pull requests merged in 2025-04, with the labels that each got.

#2893 Fights todos
  Core/src/core/fights/FightController.ts
  Core/src/core/fights/FightView.ts
  Core/src/core/fights/fighter/AiPlayerFighter.ts
  Core/src/core/fights/fighter/PlayerFighter.ts
  Discord/src/commands/player/FightCommand.ts
  Lang/fr/commands.json
  Lib/src/packets/fights/FightIntroductionPacket.ts
Labels: command, core, discord

#2899 Fix switch unblock #2897
  Core/src/commands/player/SwitchCommand.ts
Labels: bug

#2879 fix items
  Core/resources/weapons/87.json
  Core/resources/weapons/88.json
  Core/resources/weapons/89.json
  Core/src/data/Armor.ts
  Core/src/data/Weapon.ts
Labels: core, test

#2873 add new staff members to the SE staffMembers
  Lang/fr/smallEvents.json
Labels: event / mini event

#2906 fix skip mission #2904
  Core/src/commands/mission/MissionShopCommand.ts
Labels: core, test

#2917 Fix new accounts, prevent from creating them unintentionally and bett…
  Core/src/commands/guild/GuildCommand.ts
  Core/src/commands/guild/GuildInviteCommand.ts
  Core/src/commands/mission/MissionsCommand.ts
  Core/src/commands/player/InventoryCommand.ts
  Core/src/commands/player/ProfileCommand.ts
  Core/src/commands/player/SellCommand.ts
  Core/src/commands/player/UnlockCommand.ts
  Core/src/core/database/game/models/Player.ts
  Core/src/core/utils/CommandUtils.ts
  Discord/src/commands/guild/GuildInviteCommand.ts
  Discord/src/commands/mission/MissionsCommand.ts
  Discord/src/commands/player/InventoryCommand.ts
  Discord/src/packetHandlers/handlers/commands/guild/GuildInviteCommandPacketHandlers.ts
  Discord/src/packetHandlers/handlers/commands/player/ProfileCommandPacketHandlers.ts
  Discord/src/packetHandlers/handlers/commands/player/UnlockCommandPacketHandlers.ts
  Discord/src/utils/ErrorUtils.ts
  Discord/src/utils/PacketUtils.ts
  Lang/fr/error.json
  Lib/src/packets/commands/CommandGuildInvitePacket.ts
Labels: bug

#2920 Fix bot mentions keycloak account creation #2915
  Discord/src/commands/CommandsManager.ts
  Lang/de/bot.json
  Lang/en/bot.json
  Lang/es/bot.json
  Lang/it/bot.json
  Lang/pt/bot.json
  Lib/src/keycloak/KeycloakUtils.ts
Labels: bug

#2928 Ajout des items donateurs #2457
  Core/resources/armors/62.json
  Core/resources/armors/63.json
  Core/resources/objects/90.json
  Core/resources/potions/94.json
  Core/resources/weapons/95.json
  Core/resources/weapons/96.json
  Core/resources/weapons/97.json
  Lang/fr/models.json
Labels: items / new pet / new monster

#2927 Small fixes
  Core/src/data/Class.ts
Labels: refactoring

#2941 Always log unhandled and uncaught exception in the console
  Discord/src/bot/DraftBotShard.ts
Labels: bug

#2925 Draftbot v5 remove emoticons from constant to use DraftbotIcons and fix some bugs
  Core/src/commands/guild/GuildDailyCommand.ts
  Core/src/commands/mission/MissionShopCommand.ts
  Core/src/core/fights/actions/interfaces/alterations/concentrated.ts
  Core/src/core/smallEvents/interactOtherPlayers.ts
  Core/src/core/smallEvents/pet.ts
  Core/src/data/Pet.ts
  Discord/src/commands/player/ProfileCommand.ts
  Discord/src/commands/player/ReportCommand.ts
  Discord/src/packetHandlers/handlers/SmallEventsHandler.ts
  Discord/src/smallEvents/epicItemShop.ts
  Discord/src/smallEvents/shop.ts
  Discord/src/utils/DisplayUtils.ts
  Lang/en/commands.json
  Lang/fr/commands.json
  Lib/src/DraftBotIcons.ts
  Lib/src/constants/BadgeConstants.ts
  Lib/src/constants/Constants.ts
  Lib/src/constants/PetConstants.ts
  Lib/src/constants/SmallEventConstants.ts
  Lib/src/utils/TimeUtils.ts
Labels: typo / visu, refactoring

#2949 parseInt fixing #2633
  Core/src/core/database/logs/LogsDatabase.ts
  Core/src/data/DataController.ts
  Discord/src/commands/player/ClassesCommand.ts
  Discord/src/commands/player/ClassesInfoCommand.ts
  Discord/src/translations/i18n.ts
  Discord/src/utils/DiscordCollectorUtils.ts
  Lib/src/utils/RandomUtils.ts
Labels: refactoring

#2952 Fix error objects logging #2948
  Core/src/commands/admin/TestCommand.ts
  Core/src/commands/player/ReportCommand.ts
  Core/src/core/fights/FightController.ts
  Core/src/index.ts
  Discord/src/announcements/DiscordAnnouncement.ts
  Discord/src/bot/DiscordMQTT.ts
  Discord/src/bot/DraftBotShard.ts
  Discord/src/commands/CommandsManager.ts
  Discord/src/commands/player/HelpCommand.ts
  Discord/src/index.ts
  Discord/src/messages/DraftbotInteraction.ts
  Discord/src/notifications/NotificationsHandler.ts
  Discord/src/translations/i18n.ts
  Discord/src/utils/EmoteUtils.ts
  Lib/src/logs/Logger.ts
  Lib/src/packets/PacketListener.ts
Labels: bug, not end user

#2957 Improve MQTT code
  Core/src/core/utils/PacketUtils.ts
  Discord/src/bot/DiscordMQTT.ts
  Discord/src/utils/PacketUtils.ts
  Lib/src/utils/MqttTopicUtils.ts
Labels: core, not end user

#2961 Fight points regen loop
  Core/src/core/bot/DraftBot.ts
Labels: core

#2977 Fix #2975 and other shop issues
  Core/src/core/utils/ShopUtils.ts
  Discord/src/commands/player/ShopCommand.ts
  Lang/fr/error.json
Labels: bug

#2989 small balance changes and fixes
  Core/src/core/fights/actions/interfaces/players/energeticAttack.ts
  Core/src/core/fights/actions/interfaces/players/poisonousAttack.ts
  Core/src/core/fights/actions/interfaces/players/ramAttack.ts
Labels: balancing

#3009 Suppression de conseils obsolètes
  Lang/fr/advices.json
Labels: typo / visu

#3012 Fix missing successful missions shop successful transaction header
  Discord/src/commands/mission/MissionShop.ts
  Lang/fr/commands.json
Labels: typo / visu

#3021 fix #2998 + MANY other issues with witch event and refactoring
  Core/src/core/smallEvents/witch.ts
  Core/src/core/smallEvents/witch/bat.ts
  Core/src/core/smallEvents/witch/bigWarm.ts
  Core/src/core/smallEvents/witch/blood.ts
  Core/src/core/smallEvents/witch/bone.ts
  Core/src/core/smallEvents/witch/chicken.ts
  Core/src/core/smallEvents/witch/cool.ts
  Core/src/core/smallEvents/witch/crystalBall.ts
  Core/src/core/smallEvents/witch/distiller.ts
  Core/src/core/smallEvents/witch/eye.ts
  Core/src/core/smallEvents/witch/frog.ts
  Core/src/core/smallEvents/witch/greenApple.ts
  Core/src/core/smallEvents/witch/heart.ts
  Core/src/core/smallEvents/witch/mushroom.ts
  Core/src/core/smallEvents/witch/rat.ts
  Core/src/core/smallEvents/witch/redApple.ts
  Core/src/core/smallEvents/witch/rose.ts
  Core/src/core/smallEvents/witch/scorpion.ts
  Core/src/core/smallEvents/witch/smallWarm.ts
  Core/src/core/smallEvents/witch/snake.ts
  Core/src/core/smallEvents/witch/spider.ts
  Core/src/core/smallEvents/witch/teeth.ts
  Core/src/core/smallEvents/witch/turtle.ts
  Core/src/core/smallEvents/witch/wiltedRose.ts
  Core/src/core/smallEvents/witch/worm.ts
  Core/src/data/WitchAction.ts
  Discord/src/smallEvents/witch.ts
  Lang/fr/commands.json
  Lang/fr/smallEvents.json
  Lib/src/packets/smallEvents/SmallEventWitchPacket.ts
Labels: bug, event / mini event, refactoring

#3010 FIX 2987
  Core/src/core/maps/MapCache.ts
Labels: bug

#3024 fix wrong user language on pet transfer #3007
  Discord/src/commands/pet/PetTransferCommand.ts
Labels: bug

#3022 Display the cost if the pet is feisty #3019
  Discord/src/commands/pet/PetFreeCommand.ts
  Lang/fr/commands.json
Labels: typo / visu

#3025 fix #3018
  Discord/src/commands/mission/MissionsCommand.ts
  Lang/fr/commands.json
Labels: bug

#3027 Fix Typo
  Discord/src/smallEvents/witch.ts
  Discord/src/utils/DisplayUtils.ts
  Discord/src/utils/EmoteUtils.ts
  Lib/src/DraftBotIcons.ts
Labels: typo / visu

#3034 re adding some important mds
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
Labels: github, legal, not end user

#3050 fix mds
  CONTRIBUTING.md
  SECURITY.md
Labels: typo / visu, not end user

#3058 Fix2864
  Core/src/core/database/game/models/Player.ts
  Core/src/core/smallEvents/bonusGuildPVEIsland.ts
Labels: bug

#3059 fix time alteration bigWait on se witch
  Core/resources/witch/bigWait.json
Labels: bug

#3061 Fix #3043
  Core/src/data/WitchAction.ts
  Discord/src/smallEvents/witch.ts
Labels: bug

#3063 Unblock Player if not enough gems on SE goToPVEIsland #3062
  Core/src/core/smallEvents/goToPVEIsland.ts
Labels: bug

#3070 Fix guild kick
  Core/src/commands/guild/GuildKickCommand.ts
Labels: bug

#3072 fix french name top glory
  Lang/fr/discordBuilder.json
Labels: typo / visu

#3076 fix #3074
  Lang/fr/commands.json
Labels: typo / visu

#3078 fix display #3077
  Discord/src/utils/DiscordItemUtils.ts
  Lib/src/constants/ItemConstants.ts
Labels: typo / visu

#3082 time travel back to continent change for 8min instead of 10m
  Core/resources/mapLinks/1996.json
  Core/resources/mapLinks/1997.json
  Core/resources/mapLinks/1998.json
  Core/resources/mapLinks/1999.json
Labels: core

#3088 Fix #3066
  Core/src/core/database/logs/migrations/010-possibilities-emoji-to-id.json
  Core/src/core/database/logs/migrations/010-possibilities-v5.ts
Labels: bug, database

#3091 fix map #3079
  Core/src/commands/player/MapCommand.ts
Labels: bug

#3092 fix display guild max level #3090
  Core/src/commands/pet/PetSellCommand.ts
  Discord/src/commands/pet/PetSellCommand.ts
  Lib/src/packets/commands/CommandPetSellPacket.ts
Labels: typo / visu

#3098 Fix #3093
  Core/src/commands/pet/PetSellCommand.ts
  Discord/src/commands/pet/PetSellCommand.ts
  Lib/src/packets/interaction/ReactionCollectorPetSell.ts
Labels: bug

#3102 Fix #3095 + maintenance bypass and errors
  Core/src/index.ts
  Discord/src/commands/CommandsManager.ts
  Discord/src/commands/admin/GiveBadgeCommand.ts
  Discord/src/commands/guild/GuildCommand.ts
  Discord/src/commands/guild/GuildCreateCommand.ts
  Discord/src/commands/guild/GuildDailyCommand.ts
  Discord/src/commands/guild/GuildInviteCommand.ts
  Discord/src/commands/guild/GuildKickCommand.ts
  Discord/src/commands/guild/GuildShopCommand.ts
  Discord/src/commands/mission/MissionsCommand.ts
  Discord/src/commands/pet/PetFreeCommand.ts
  Discord/src/commands/pet/PetNickCommand.ts
  Discord/src/commands/player/DailyBonusCommand.ts
  Discord/src/commands/player/InventoryCommand.ts
  Discord/src/commands/player/ShopCommand.ts
  Discord/src/commands/player/TopCommand.ts
  Discord/src/commands/player/UnlockCommand.ts
  Discord/src/messages/DraftBotErrorEmbed.ts
  Discord/src/packetHandlers/handlers/CommandRequirementHandlers.ts
  Discord/src/packetHandlers/handlers/ErrorHandler.ts
  Discord/src/packetHandlers/handlers/EventsHandlers.ts
  Discord/src/packetHandlers/handlers/commands/guild/GuildInviteCommandPacketHandlers.ts
  Discord/src/packetHandlers/handlers/commands/player/JoinBoatCommandPacketHandlers.ts
  Discord/src/packetHandlers/handlers/commands/player/ProfileCommandPacketHandlers.ts
  Discord/src/packetHandlers/handlers/commands/player/UnlockCommandPacketHandlers.ts
  Discord/src/utils/ErrorUtils.ts
  Discord/src/utils/PacketUtils.ts
Labels: bug

#3121 5.0.0.b translations
  Lang/de/bot.json
  Lang/de/smallEvents.json
  Lang/en/bot.json
  Lang/en/smallEvents.json
  Lang/es/bot.json
  Lang/es/smallEvents.json
  Lang/it/bot.json
  Lang/it/smallEvents.json
  Lang/pt/bot.json
  Lang/pt/smallEvents.json
Labels: translations

#3131 fix pet assistance slipping #3126
  Core/src/core/fights/actions/interfaces/pets/slipping.ts
Labels: bug

#3133 Fix #3107
  Core/src/core/CoreConstants.ts
  Core/src/index.ts
Labels: bug, core

#3134 Fix #3112
  Core/src/core/database/logs/LogsDatabase.ts
Labels: bug

#3143 check keycloakID in Core for collector guildInvite #3097
  Core/src/commands/guild/GuildInviteCommand.ts
Labels: core

#3144 change the embed title if a user is mentioned on pet sell #3099
  Discord/src/commands/pet/PetSellCommand.ts
  Lang/fr/commands.json
Labels: command, typo / visu

#3148 fix #3124
  Core/src/core/database/game/models/Player.ts
  Discord/src/packetHandlers/handlers/EventsHandlers.ts
  Lib/src/packets/events/PlayerLevelUpPacket.ts
Labels: bug

#3154 Crowdin changes
  Core/src/commands/player/ClassesCommand.ts
  Lang/de/commands.json
  Lang/en/advices.json
  Lang/en/bot.json
  Lang/en/commands.json
  Lang/en/smallEvents.json
  Lang/es/commands.json
  Lang/es/smallEvents.json
  Lang/it/commands.json
  Lang/it/smallEvents.json
  Lang/pt/commands.json
  Lang/pt/smallEvents.json
  Lib/src/utils/TimeUtils.ts
Labels: translations

#3166 check if the last action exists for chargingAttack in veteran AI #3165
  Core/src/core/fights/aiClassBehaviors/VeteranFightBehavior.ts
Labels: bug

#3177 display properly minutes malus SE goblet games #3174
  Discord/src/packetHandlers/handlers/SmallEventsHandler.ts
Labels: typo / visu

#3179 fix se class #3178
  Core/src/core/smallEvents/class.ts
Labels: bug

#3186 ajout d'un workflow GitHub pour envoyer des conseils quotidiens sur D…
  .github/workflows/daily-advice.yml
Labels: bug, github

#3198 Fix embed wrongly assuming someone alone was with a guild member upon joining the boat (or the opposite) #3197
  Discord/src/packetHandlers/handlers/SmallEventsHandler.ts
  Lang/fr/smallEvents.json
Labels: typo / visu

#3199 Fix wrong username on unlock header #3187
  Discord/src/commands/player/UnlockCommand.ts
Labels: typo / visu

#3205 fix #3191
  Core/src/commands/guild/GuildInviteCommand.ts
Labels: bug

#3212 Fixglory
  Core/src/commands/player/FightCommand.ts
Labels: bug

#3215 first draft at unit tests #3029
  .deepsource.toml
  .github/workflows/tests.yml
  Core/.gitignore
  Core/__tests__/core/utils/MathUtils.test.ts
  Core/package.json
  Core/vitest.config.mts
  Core/yarn.lock
  Discord/.gitignore
  Discord/__tests__/utils/StringUtils.test.ts
  Discord/package.json
  Discord/vitest.config.mts
  Discord/yarn.lock
  Lib/.gitignore
  Lib/package.json
  Lib/tests/utils/StringUtils.test.ts
  Lib/vitest.config.mts
  Lib/yarn.lock
Labels: test
