Repository Crownicles/Crownicles, pull requests merged in 2025-03, with the labels that each got.

#2787 Fix #2786
  Core/src/commands/pet/PetCommand.ts
  Discord/src/commands/pet/PetCommand.ts
  Lib/src/packets/commands/CommandPetPacket.ts
Labels: bug

#2795 Add user avatar to sell choice embed
  Discord/src/commands/player/SellCommand.ts
Labels: command

#2822 GuildStorageCommand #2744
  Core/src/commands/guild/GuildInviteCommand.ts
  Core/src/commands/guild/GuildStorageCommand.ts
  Core/src/core/database/game/models/Player.ts
  Core/src/core/smallEvents/bonusGuildPVEIsland.ts
  Core/src/core/smallEvents/winGuildXP.ts
  Discord/src/commands/guild/GuildStorageCommand.ts
  Discord/src/packetHandlers/handlers/commands/guild/GuildStoragePacketHandlers.ts
  Lang/en/discordBuilder.json
  Lang/fr/commands.json
  Lang/fr/discordBuilder.json
  Lang/fr/models.json
  Lib/src/constants/GuildConstants.ts
  Lib/src/packets/commands/CommandGuildStoragePacket.ts
Labels: command

#2827 Fix code for windows native
  Lib/src/database/Database.ts
Labels: bug

#2830 Mit license -> GPL3 for Draftbot V5
  LICENSE
  README.md
Labels: legal

#2832 Merge v4 into v5
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  Core/resources/armors/52.json
  Core/resources/armors/58.json
  Core/resources/armors/59.json
  Core/resources/armors/60.json
  Core/resources/armors/61.json
  Core/resources/events/40.json
  Core/resources/events/64.json
  Core/resources/events/71.json
  Core/resources/events/74.json
  Core/resources/mapLinks/84.json
  Core/resources/missions/drinkEnergyPotion.json
  Core/resources/missions/gainRage.json
  Core/resources/missions/guildHasPoints.json
  Core/resources/missions/joinMemberOnBoat.json
  Core/resources/missions/joinPVEIsland.json
  Core/resources/missions/meetHermit.json
  Core/resources/missions/spendMoney.json
  Core/resources/missions/wealthyPayForPVEIsland.json
  Core/resources/missions/winBoss.json
  Core/resources/objects/82.json
  Core/resources/objects/83.json
  Core/resources/objects/84.json
  Core/resources/objects/85.json
  Core/resources/objects/86.json
  Core/resources/objects/87.json
  Core/resources/objects/88.json
  Core/resources/objects/89.json
  Core/resources/potions/90.json
  Core/resources/potions/91.json
  Core/resources/potions/92.json
  Core/resources/potions/93.json
  Core/resources/weapons/89.json
  Core/resources/weapons/90.json
  Core/resources/weapons/91.json
  Core/resources/weapons/92.json
  Core/resources/weapons/93.json
  Core/resources/weapons/94.json
  Core/src/core/database/game/models/Player.ts
  Core/src/core/fights/actions/interfaces/players/guildAttack.ts
  Core/src/core/smallEvents/fightPet.ts
  Core/src/core/smallEvents/goToPVEIsland.ts
  Core/src/core/utils/ItemUtils.ts
  Core/src/data/MapLink.ts
  Discord/src/commands/CommandsManager.ts
  Lang/fr/advices.json
  Lang/fr/bot.json
  Lang/fr/discordBuilder.json
  Lang/fr/error.json
  Lang/fr/events.json
  Lang/fr/models.json
  Lib/src/DraftBotIcons.ts
  Lib/src/types/Effect.ts
Labels: enhancement, event / mini event, items / new pet / new monster

#2835 Guild kick fixes
  Core/src/commands/guild/GuildKickCommand.ts
  Core/src/core/utils/BlockingUtils.ts
  Discord/src/packetHandlers/handlers/ErrorHandler.ts
  Discord/src/packetHandlers/handlers/commands/guild/GuildKickCommandPacketHandlers.ts
  Lang/fr/commands.json
  Lib/src/packets/commands/CommandGuildKickPacket.ts
Labels: bug, command

#2773 JoinBoat command
  Core/src/commands/admin/testCommands/Guild/ResetJoinBoatTestCommand.ts
  Core/src/commands/admin/testCommands/Guild/RollbackGuildJoin.ts
  Core/src/commands/admin/testCommands/Map/TravelTestCommand.ts
  Core/src/commands/player/JoinBoatCommand.ts
  Core/src/core/database/game/models/PlayerMissionsInfo.ts
  Core/src/core/database/logs/LogsReadRequests.ts
  Core/src/core/maps/Maps.ts
  Core/src/core/maps/TravelTime.ts
  Core/src/core/smallEvents/goToPVEIsland.ts
  Core/src/core/utils/ShopUtils.ts
  Core/src/data/events/PossibilityOutcome.ts
  Discord/src/commands/guild/GuildCommand.ts
  Discord/src/commands/player/JoinBoatCommand.ts
  Discord/src/packetHandlers/handlers/ReactionCollectorHandlers.ts
  Discord/src/packetHandlers/handlers/SmallEventsHandler.ts
  Discord/src/packetHandlers/handlers/commands/player/JoinBoatCommandPacketHandlers.ts
  Lang/en/discordBuilder.json
  Lang/fr/commands.json
  Lang/fr/discordBuilder.json
  Lang/fr/smallEvents.json
  Lib/src/DraftBotIcons.ts
  Lib/src/constants/Constants.ts
  Lib/src/constants/LogsConstants.ts
  Lib/src/packets/commands/CommandJoinBoatPacket.ts
  Lib/src/packets/interaction/ReactionCollectorJoinBoat.ts
  Lib/src/packets/smallEvents/SmallEventGoToPVEIslandPacket.ts
  Lib/src/utils/TimeUtils.ts
Labels: command

#2863 Fix item differences between v4 and v5 #2860
  Core/resources/objects/28.json
  Core/resources/objects/3.json
  Core/resources/objects/4.json
  Core/resources/objects/50.json
  Core/resources/objects/62.json
  Core/resources/objects/64.json
  Core/resources/objects/67.json
Labels: balancing

#2883 Added i18n for /guildshelter #2881
  Discord/src/commands/guild/GuildShelterCommand.ts
  Lang/fr/commands.json
Labels: typo / visu

#2885 Prevent player defending two players at the same time #2855
  Core/src/commands/player/FightCommand.ts
Labels: bug
