Repository Crownicles/Crownicles, pull requests merged in 2025-06, with the labels that each got.

#3384 Ajout types attaques https://github.com/DraftBot-A-Discord-Adventure/…
  Lang/fr/smallEvents.json
Labels: event / mini event

#3390 fix display guild #3389
  Discord/src/commands/guild/GuildCommand.ts
Labels: bug

#3392 Issue 3388
  Core/src/commands/admin/testCommands/Player/MarkAllPetsSeenDwarfTestCommand.ts
  Core/src/commands/mission/MissionShopCommand.ts
  Core/src/core/database/game/models/DwarfPetsSeen.ts
  Discord/src/commands/mission/MissionShop.ts
  Lang/fr/commands.json
  Lib/src/constants/PetConstants.ts
  Lib/src/packets/commands/CommandMissionShopPacket.ts
Labels: enhancement, small feature

#3426 fix guildshop #3425
  Discord/src/commands/guild/GuildShopCommand.ts
Labels: bug

#3396 Notifications guildKick and guildElder
  Core/src/commands/guild/GuildElderCommand.ts
  Core/src/commands/guild/GuildElderRemoveCommand.ts
  Core/src/commands/guild/GuildKickCommand.ts
  Core/src/commands/guild/GuildLeaveCommand.ts
  Discord/src/commands/notifications/NotificationsCommand.ts
  Discord/src/database/discord/migrations/004-add-guild-kick-notification.ts
  Discord/src/database/discord/migrations/005-add-guild-status-change-notification.ts
  Discord/src/database/discord/models/NotificationsConfiguration.ts
  Discord/src/notifications/NotificationType.ts
  Discord/src/notifications/NotificationsHandler.ts
  Lang/fr/bot.json
  Lang/fr/commands.json
  Lib/src/CrowniclesIcons.ts
  Lib/src/constants/NotificationsConstants.ts
  Lib/src/packets/notifications/GuildKickNotificationPacket.ts
  Lib/src/packets/notifications/GuildStatusChangeNotificationPacket.ts
Labels: enhancement

#3405 Fix key effect
  Core/resources/events/56.json
  Core/resources/events/69.json
  Core/src/core/database/logs/migrations/010-possibilities-emoji-to-id.json
  Core/src/core/database/logs/migrations/013-fix-possibility-name-possibilities-log.ts
  Lang/fr/events.json
  Lib/src/CrowniclesIcons.ts
Labels: bug, core

#3445 Fix benediction
  Core/src/core/fights/aiClassBehaviors/KnightFightBehavior.ts
Labels: bug
